// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGb1-d1u2vfotS824t48filELB4S4VZSw',
    appId: '1:900635189729:web:6c0fda06c8cb30e97172a0',
    messagingSenderId: '900635189729',
    projectId: 'evently-a9a39',
    authDomain: 'evently-a9a39.firebaseapp.com',
    storageBucket: 'evently-a9a39.firebasestorage.app',
    measurementId: 'G-PLJRGPHRF2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHnAb465owuB0gRJOTvtQ3dg8Xs3r1FEQ',
    appId: '1:900635189729:android:36154c4694a976d27172a0',
    messagingSenderId: '900635189729',
    projectId: 'evently-a9a39',
    storageBucket: 'evently-a9a39.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_OEQ1CpuxuRAv-tuzYyFanu73iPNDkuE',
    appId: '1:900635189729:ios:7edd72fec8bc14aa7172a0',
    messagingSenderId: '900635189729',
    projectId: 'evently-a9a39',
    storageBucket: 'evently-a9a39.firebasestorage.app',
    iosBundleId: 'com.example.evently',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_OEQ1CpuxuRAv-tuzYyFanu73iPNDkuE',
    appId: '1:900635189729:ios:7edd72fec8bc14aa7172a0',
    messagingSenderId: '900635189729',
    projectId: 'evently-a9a39',
    storageBucket: 'evently-a9a39.firebasestorage.app',
    iosBundleId: 'com.example.evently',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGb1-d1u2vfotS824t48filELB4S4VZSw',
    appId: '1:900635189729:web:76e078da7a7b02557172a0',
    messagingSenderId: '900635189729',
    projectId: 'evently-a9a39',
    authDomain: 'evently-a9a39.firebaseapp.com',
    storageBucket: 'evently-a9a39.firebasestorage.app',
    measurementId: 'G-V9R3R70WXP',
  );
}
